spring:
  # MySQL 주소
  datasource:
    url: jdbc:mysql://localhost:3306/nemo_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USERNAME}
    password: ${PASSWORD}

  # redis 주소
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      password: # 로컬에서는 비밀번호 없음

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  tracing:
    sampling:
      probability: 0.0  # 로컬에서는 트레이싱 비활성화
  otlp:
    metrics:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    com.nemo: DEBUG

sentry:
  enabled: false
