spring:
  application:
    name: nemo

  # 활성 프로필
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # 파일 업로드 설정 (이미지 파일)
  servlet:
    multipart:
      max-file-size: ${IMAGE_FILE_BYTE:10MB}
      max-request-size: ${IMAGE_REQUEST_BYTE:50MB}

  # MySQL 드라이버
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MySQL 방언
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        # sql 포매팅 (가독성 향상)
        format_sql: true

  messages:
    basename: validation
    encoding: UTF-8

oauth:
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-validity: ${REFRESH_TOKEN_EXPIRATION:604800000}

server:
  forward-headers-strategy: framework

# 이미지 파일 s3 사용
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}

# AI 서버 주소
ai:
  service:
    url: ${AI_SERVICE_URL}
    endpoints:
      group-generate: /ai/v1/groups/information
      group-chatbot:
        group-recommend-freeform: /ai/v2/groups/recommendations/freeform
        group-recommend-questions: /ai/v2/groups/recommendations/questions
        group-recommend: /ai/v2/groups/recommendations
        group-websocket: ${GROUP_CHATBOT_URI}
      group-data:
        group-create: /ai/v2/groups
        group-delete: /ai/v2/groups/delete
        group-join: /ai/v2/groups/participants
        group-leave: /ai/v2/groups/participants/delete
