spring:
  # MySQL 주소
  datasource:
    url: jdbc:mysql://localhost:3306/nemo_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USERNAME}
    password: ${PASSWORD}

  # redis 주소
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      password: # 로컬에서는 비밀번호 없음

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    producer:
      acks: all  # idempotent producer를 위해 all로 설정
      retries: 3   # 전송 실패시 재시도 횟수
      batch-size: 1024   # 한 번에 보낼 메시지들을 모아두는 배치 크기
      properties:
        max.in.flight.requests.per.connection: 1   # 순서 보장
        enable.idempotence: true   # 중복 방지
        linger.ms: 0
    consumer:
      group-id: nemo-group-local
      auto-offset-reset: latest  # 개발시 최신 메시지만

management:
  tracing:
    sampling:
      probability: 0.0  # 로컬에서는 트레이싱 비활성화
  otlp:
    metrics:
      export:
        enabled: false
    tracing:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    com.nemo: DEBUG

sentry:
  enabled: false
