spring:
  application:
    name: nemo

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  servlet:
    multipart:
      max-file-size: ${IMAGE_FILE_BYTE}
      max-request-size: ${IMAGE_REQUEST_BYTE}

  datasource:
    url: jdbc:mysql://${DB_URL}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s
      password: ${REDIS_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  messages:
    basename: validation
    encoding: UTF-8

oauth:
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-validity: ${REFRESH_TOKEN_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: never

server:
  forward-headers-strategy: framework

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ${AWS_REGION}

ai:
  service:
    url: ${AI_SERVICE_URL}
    endpoints:
      group-generate: /ai/v1/group/information
      group-chatbot:
        group-recommend-freeform: /ai/v2/groups/recommendations/freeform
        group-recommend-questions: /ai/v2/groups/recommendations/questions
        group-recommend: /ai/v2/groups/recommendations
      group-data:
        group-create: /ai/v2/groups
        group-delete: /ai/v2/groups/delete
        group-participant: /ai/v2/groups/participants
        group-leave: /ai/v2/groups/participants/delete




sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: ${SENTRY_RELEASE}
  traces-sample-rate: ${SENTRY_SAMPLE_RATE:0.1}
  send-default-pii: ${SENTRY_SEND_PII:false}
  enable-tracing: true
  enabled: false
