spring:
  datasource:
    url: jdbc:mysql://${DB_URL}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT:6379}
      timeout: 2s
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: true
    tracing:
      endpoint: http://35.216.67.116:4318
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.nemo: INFO
    root: INFO
  file:
    name: logs/nemo.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV:production}
  release: ${SENTRY_RELEASE}
  traces-sample-rate: ${SENTRY_SAMPLE_RATE:0.1}
  send-default-pii: ${SENTRY_SEND_PII:false}
  enable-tracing: true
  enabled: true
