spring:
  datasource:
    url: jdbc:mysql://${DB_URL}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT:6379}
      timeout: 2s
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  kafka:
    producer:
      acks: all  # 모든 replica가 메시지를 받았을 때만 성공으로 처리
      retries: 5   # 전송 실패시 재시도 횟수
      batch-size: 32768   # 한 번에 보낼 메시지들을 모아두는 배치 크기
      properties:
        max.in.flight.requests.per.connection: 1   # 순서 보장
        enable.idempotence: true   # 중복 방지
        linger.ms: 5   # 배치가 가득 안 차도 5ms 후에는 전송
    consumer:
      group-id: nemo-group-prod
      auto-offset-reset: earliest  # 개발시 최신 메시지만
      max-poll-records: 100   # 배치 처리 최적화

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: true
    tracing:
      endpoint: http://35.216.67.116:4318
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.nemo: INFO
    root: INFO
  file:
    name: logs/nemo.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV:production}
  release: ${SENTRY_RELEASE}
  traces-sample-rate: ${SENTRY_SAMPLE_RATE:0.1}
  send-default-pii: ${SENTRY_SEND_PII:false}
  enable-tracing: true
  enabled: true
