name: Backend CI/CD

on:
  push:
    branches: [ infra/ci-cd ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar -x test

      - name: Upload JAR to Server
        run: |
          scp ./6-nemo-be/build/libs/nemo-server-0.0.1-SNAPSHOT.jar \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/nemo/backend/jar-backups/

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/nemo/backend/scripts
            bash deploy_ci_cd.sh
