name: Backend CD for v2-Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: '릴리즈 버전 태그 (예: v1.3.0)'
        required: true

jobs:
  build-and-deploy:
    name: Build & Deploy to Prod MIG
    runs-on: ubuntu-latest

    env:
      REGION: asia-northeast3
      REPOSITORY: registry
      SERVICE: backend
      ENVIRONMENT: prod
      DEPLOY_SCRIPT: cloud/v2/scripts/deploy.sh
      GCP_PROJECT_ID_PROD: '${{ secrets.GCP_PROJECT_ID_PROD }}'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_PROD }}'

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID_PROD }}
      
      - name: Set image tags and URI
        run: |
          TIME_TAG="${{ env.ENVIRONMENT }}-$(TZ=Asia/Seoul date +'%Y%m%d-%H%M')"
          VERSION_TAG="prod-${{ github.event.inputs.version }}"
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_PROD }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}"

          echo "TIME_TAG=$TIME_TAG" >> $GITHUB_ENV
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Registry Auth
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY_PROD }}

      - name: Gradle Build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: ./gradlew build -x test --no-daemon

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t "${IMAGE_URI}:${TIME_TAG}" \
            -t "${IMAGE_URI}:$VERSION_TAG" \
            -t "${IMAGE_URI}:${{ env.ENVIRONMENT }}-latest" \
            --output=type=image,push=true .
      
      - name: Checkout cloud repo for deploy script
        uses: actions/checkout@v3
        with:
          repository: 100-hours-a-week/6-nemo-cloud
          path: cloud
          token: ${{ secrets.CLOUD_REPO_TOKEN }}
      
      - name: Execute deploy script
        run: |
          bash ${{ env.DEPLOY_SCRIPT }} ${{ env.SERVICE }} ${{ env.ENVIRONMENT }}

      
