name: Backend CI for v2-prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: '릴리즈 버전 태그 (예: v1.3.0)'
        required: true

jobs:
  build-and-deploy:
    name: Build & Push
    runs-on: ubuntu-latest
    environment: prod

    env:
      REGION: asia-northeast3
      REPOSITORY: registry
      SERVICE: backend
      ENVIRONMENT: prod
      
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_PROD }}'

    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID_PROD }}

    - name: Set image tags and URI
      run: |
        TIME_TAG="${{ env.ENVIRONMENT }}-$(TZ=Asia/Seoul date +'%Y%m%d-%H%M')"
        echo "TIME_TAG=$TIME_TAG" >> $GITHUB_ENV

        VERSION_TAG="prod-${{ github.event.inputs.version }}"
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

        IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_PROD }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}"
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Gradle Build
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: |
        ./gradlew clean build --no-daemon

    - name: Build and Push Docker Image
      run: |
        docker buildx build \
          --no-cache \
          --platform linux/amd64 \
          -t "${IMAGE_URI}:${TIME_TAG}" \
          -t "${IMAGE_URI}:${{ env.ENVIRONMENT }}-latest" \
          -t "${IMAGE_URI}:${VERSION_TAG}" \
          --push .
